// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbpljsngllzchffofgjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicGxqc25nbGx6Y2hmZm9mZ2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNjA0OTYsImV4cCI6MjA4NTkzNjQ5Nn0.BeJ3lJS2jcyW6OshGsEBnWQEqBX5OJelXg459BzurpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});